using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HotelManagement.Entity.Restaurant
{
    public class RestaurantBillBO
    {
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public int BillId { get; set; }
        public int SOrderId { get; set; }
        public int RefundId { get; set; }
        public string RefundRemarks { get; set; }
        public bool IsBillSettlement { get; set; }
        public bool IsBillReSettlement { get; set; }
        public int CostCenterId { get; set; }
        public string CostCenter { get; set; }
        public string CostCenterType { get; set; }
        public string StringBillDate { get; set; }
        public DateTime BillDate { get; set; }
        public DateTime BillPaymentDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerAddress { get; set; }
        public string BillNumber { get; set; }
        public string BillStatus { get; set; }
        public string Remarks { get; set; }
        public string Subject { get; set; }
        public int PaxQuantity { get; set; }
        public int TableId { get; set; }
        public int BankId { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public DateTime? ExpireDate { get; set; }
        public string CardHolderName { get; set; }
        public int RoomId { get; set; }
        public int RegistrationId { get; set; }
        public string CheckOutDate { get; set; }
        public int PendingBillQuantity { get; set; }
        public decimal SalesAmount { get; set; }
        public decimal InvoiceServiceRate { get; set; }
        public bool IsComplementary { get; set; }
        public bool IsNonChargeable { get; set; }
        public string DiscountType { get; set; }
        public int DiscountTransactionId { get; set; }
        public string BusinessPromotionIdNPercentAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal CalculatedDiscountAmount { get; set; }
        public bool IsOnlyRateEffectEnable { get; set; }
        public bool IsInvoiceServiceChargeEnable { get; set; }
        public bool IsInvoiceVatAmountEnable { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal VatAmount { get; set; }
        public bool IsInvoiceCitySDChargeEnable { get; set; }
        public decimal CitySDCharge { get; set; }
        public bool IsInvoiceAdditionalChargeEnable { get; set; }
        public string AdditionalChargeType { get; set; }
        public decimal AdditionalCharge { get; set; }
        public decimal PointAmount { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal RoundedAmount { get; set; }
        public decimal RoundedGrandTotal { get; set; }
        public int DealId { get; set; }
        public string SourceName { get; set; }
        public string TransactionType { get; set; }
        public Int64? TransactionId { get; set; }
        public int? PaymentInstructionId { get; set; }
        public int? ContactId { get; set; }
        public int BillPaidBySourceId { get; set; }
        public int ClassificationId { get; set; }
        public int BillVoidBy { get; set; }
        public string BillVoidByName { get; set; }
        public string VoidDate { get; set; }
        public string VoidTime { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public int LastModifiedBy { get; set; }
        public string LastModifiedDate { get; set; }
        public int IsDayClosed { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsLocked { get; set; }
        public int KotId { get; set; }
        public string KotIds { get; set; }
        public int BearerId { get; set; }
        public string PayMode { get; set; }
        public int PayModeSourceId { get; set; }
        public decimal PaySourceCurrentBalance { get; set; }
        public bool IsBillPreviewButtonEnable { get; set; }
        public string KotDateString { get; set; }
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public decimal ItemUnit { get; set; }
        public string CreatedByUser { get; set; }
        public string CreatedDateString { get; set; }
        public string ModifiedByUser { get; set; }
        public string LastModifiedDateString { get; set; }
        public string KotStatus { get; set; }
        public string ApprovedStatus { get; set; }
        public string PaymentRemarks { get; set; }
        public string BillType { get; set; }
        public string BillingType { get; set; }
        public string BillRemarks { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalPrice { get; set; }
        public int? ReferenceBillId { get; set; }
        public int? ReturnBillId { get; set; }
        public DateTime? ReturnDate { get; set; }
        public decimal? ExchangeItemVatAmount { get; set; }
        public decimal? ExchangeItemTotal { get; set; }
        public string ReferenceBillNumber { get; set; }
        public bool IsSynced { get; set; }
        public int GLCompanyId { get; set; }
        public int ProjectId { get; set; }
        public string CompanyType { get; set; }
        public string AccountCompany { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string BinNumber { get; set; }
        public string TinNumber { get; set; }
        public string BillDescription { get; set; }
        public string BillDeclaration { get; set; }
        public string UserSignature { get; set; }
        public string CompanyName { get; set; }
        public string SDCInvoiceNumber { get; set; }
        public string QRCode { get; set; }
        public int DeliveredBy { get; set; }
        public string DeliveredByInfo { get; set; }
        public bool IsCanEdit { get; set; }
        public bool IsCanDelete { get; set; }
        public bool IsCanChecked { get; set; }
        public bool IsCanApproved { get; set; }
    }
}
