TRUNCATE TABLE BanquetBillPayment
DELETE FROM BanquetReservation
TRUNCATE TABLE BanquetReservationBillPayment
TRUNCATE TABLE BanquetReservationClassificationDiscount
TRUNCATE TABLE BanquetReservationDetail
--TRUNCATE TABLE BanquetReservation