SELECT * FROM LCCnfInfo
SELECT * FROM LCCnfPaymentLedger
SELECT * FROM LCCnfPaymentLedgerClosingDetails
SELECT * FROM LCInformation
SELECT * FROM LCInformationDetail
SELECT * FROM LCOverHeadExpense
--SELECT * FROM LCOverHeadName
SELECT * FROM LCPayment
SELECT * FROM LCPaymentLedger